In [8]:
#Question 1

import numpy as np
arr=np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [55]:
#Question 2

l1=list()
l2=list()

#accepting two list of 5 elements from the user
for i in range(5):   
    n1=int(input())
    l1.append(n1)
print(l1)

for j in range(5):
    n2=int(input())
    l2.append(n2)
print(l2)

#Converting list to numpy arrays
arr1=np.array(l1)
arr2=np.array(l2)

#Concatenating arrays
print("\nConcatenation of two arrays:")
arr3=np.concatenate([arr1,arr2])
print(arr3)

#Sorting arrays
print("\nSorting of two arrays:")
arr4=np.sort(arr3)
print(arr4)

1
2
3
4
5
[1, 2, 3, 4, 5]
0
9
6
8
7
[0, 9, 6, 8, 7]

Concatenation of two arrays:
[1 2 3 4 5 0 9 6 8 7]

Sorting of two arrays:
[0 1 2 3 4 5 6 7 8 9]


In [56]:
#Question 3

arr=np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(arr)

print("No. of dimensions: ",arr.ndim)
print("Size of array: ",arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
No. of dimensions:  2
Size of array:  9


In [45]:
#Question 4

arr1=np.array([1,2,3,4,5])
print(arr1)
print("No of dimensions ",arr1.ndim)

#Converting 1D array to 2D array using newaxis
print("\nUsing newaxis")
arr2=np.array(arr1)[np.newaxis]
print(arr2)
print("No of dimensions ",arr2.ndim)

#Converting 1D array to 2D array using expand_dims
print("\nUsing expand_dims")
arr3 = np.expand_dims(arr1, axis=0)
print(arr3)
print("No of dimensions ",arr3.ndim)


[1 2 3 4 5]
No of dimensions  1

Using newaxis
[[1 2 3 4 5]]
No of dimensions  2

Using expand_dims
[[1 2 3 4 5]]
No of dimensions  2


In [40]:
#Question 5

arr1=np.array([ [11,22,33], [44,55,66], [77,88,99] ])
arr2=np.array([ [10,20,30], [40,50,60], [70,80,90] ])
print("\nFirst square array")
print(arr1)
print("\nSecond square array")
print(arr2)

print("\nUsing hstack()")
print(np.hstack((arr1,arr2)))

print("\nUsing vstack()")
print(np.vstack((arr1,arr2)))


First square array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

Second square array
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Using hstack()
[[11 22 33 10 20 30]
 [44 55 66 40 50 60]
 [77 88 99 70 80 90]]

Using vstack()
[[11 22 33]
 [44 55 66]
 [77 88 99]
 [10 20 30]
 [40 50 60]
 [70 80 90]]


In [54]:
#Question 6

arr=np.array([1,2,3,4,5,1,9,7,8,2,5,4,1,6,9,9,9])
print("Original Array: ",arr)

uniqueValues, occurCount = np.unique(arr, return_counts=True)
print("Unique Values : " , uniqueValues)
print("Occurrence Count:", occurCount)

Original Array:  [1 2 3 4 5 1 9 7 8 2 5 4 1 6 9 9 9]
Unique Values :  [1 2 3 4 5 6 7 8 9]
Occurrence Count: [3 2 1 2 2 1 1 1 4]
